<?php

define('WPOPT_VERSION', '1.5.0');

define('WPOPT_DEBUG', $_SERVER["SERVER_ADDR"] === '127.0.0.1');

define('WPOPT_STORAGE', WP_CONTENT_DIR . '/wpopt-storage/');


if (!defined("WPOPT_CACHE_DB_THRESHOLD_STORE"))
    define('WPOPT_CACHE_DB_THRESHOLD_STORE', 0.001);

if (!defined("WPOPT_CACHE_DB_LIFETIME"))
    define('WPOPT_CACHE_DB_LIFETIME', MINUTE_IN_SECONDS * 15);

define('WPOPT_MIN_IMAGES_TO_OPTIMIZE', 10);
define('WPOPT_OPTIMIZATION_ERROR', -1);
define('WPOPT_OPTIMIZATION_SUCCESS', 1);

define('WPOPT_MARKER_BEGIN_WORDPRESS', '# BEGIN WordPress');
define('WPOPT_MARKER_END_WORDPRESS', '# END WordPress');

define('WPOPT_MARKER_BEGIN_MIME_TYPES', '# WPOPT_MARKER_BEGIN_SRV_MIME_TYPES');
define('WPOPT_MARKER_END_MIME_TYPES', '# WPOPT_MARKER_END_SRV_MIME_TYPES');


